# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
#
# XYZ Config
#
# ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓

name: xyz_config
description: Configure your app from .json, .jsonc and .yaml files
version: 0.1.2
publish_to: none
environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  xyz_utils:
    git:
      url: https://github.com/robmllze/xyz_utils.git
      ref: master
  yaml: ^3.1.0
dev_dependencies:
  lints: ^2.0.0
