##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Copyright Ⓒ Robert Mollentze, xyzand.dev
## 
## Licensing details can be found in the LICENSE file in the root directory.
## 
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_config
description: This package allows you to add configurations and language support to your apps.
repository: https://github.com/robmllze/xyz_config
version: 0.25.0

## -----------------------------------------------------------------------------

environment:

  sdk: '>= 3.3.1 < 4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  xyz_utils: ^0.51.1

  yaml: ^3.1.2
  meta: ^1.11.0
  equatable: ^2.0.5
  path: ^1.9.0

## -----------------------------------------------------------------------------

dev_dependencies:

  lints: ^3.0.0