##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Config
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_config
description: Configure your app from .json, .jsonc and .yaml files
publish_to: none
version: 0.9.0

## -----------------------------------------------------------------------------

environment:

  sdk: '>= 3.0.0 < 4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  yaml: any
  xyz_utils: any

## -----------------------------------------------------------------------------

dev_dependencies:

  lints: any
  xyz_gen: any