##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## XYZ Config
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_config
description: Configure your app from .json, .jsonc and .yaml files
publish_to: none
version: 0.7.0

## -----------------------------------------------------------------------------

environment:

  sdk: '>= 3.0.0 < 4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  yaml:
  
  xyz_utils:
    version: 0.25.0
    git:
      url: https://github.com/robmllze/xyz_utils.git

## -----------------------------------------------------------------------------

dev_dependencies:

  lints:

  xyz_gen:
    version: 0.12.0
    git:
      url: https://github.com/robmllze/xyz_gen.git