##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## X|Y|Z & Dev
##
## Copyright Ⓒ Robert Mollentze, xyzand.dev
## 
## Licensing details can be found in the LICENSE file in the root directory.
## 
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_config
description: This package is designed to help you configure your apps or add language support to your apps.
repository: https://github.com/robmllze/xyz_config
version: 0.18.1

## -----------------------------------------------------------------------------

environment:

  sdk: '>= 3.0.0 < 4.0.0'

## -----------------------------------------------------------------------------

dependencies:

  xyz_utils: ^0.47.0

  yaml: ^3.1.2
  meta: ^1.10.0
  equatable: ^2.0.5
  path: ^1.8.3

## -----------------------------------------------------------------------------

dev_dependencies:

  lints: ^3.0.0