//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

export 'configs/config.dart';
export 'configs/file_config.dart';
export 'extensions/cf_on_string_extension.dart';
export 'extensions/tr_on_string_extension.dart';
export 'managers/config_manager.dart';
export 'managers/file_config_manager.dart';
export 'managers/translation_manager.dart';
export 'refs/config_file_ref.dart';
export 'refs/config_ref.dart';
export 'refs/locale_ref.dart';
export 'utils/config_file_type.dart';
export 'utils/parse_source_for_strings_and_comments.dart';
export 'utils/src_to_data.dart';
export 'utils/translation_file_reader.dart';
