name: Publish to pub.dev

on:
  push:
    branches:
      - publish

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.2

      - name: Checkout code
        uses: actions/checkout@v3
