name: Update Changelog and Push to publish

on:
  release:
    types: [created]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.2

      - name: Update CHANGELOG.md
        env:
          RELEASE_NOTES: ${{ github.event.release.body }}
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          dart .github/scripts/update_changelog.dart "$VERSION" "$RELEASE_NOTES"

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

      - name: Commit and Push to publish
        run: |
          git checkout -b publish
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for version $VERSION"
          git push origin publish --force
