name: Update Changelog on main branch update

on:
  push:
    branches:
      - main

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Dart
        uses: dart-lang/setup-dart@v1.2

      - name: Extract version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep "version:" pubspec.yaml | sed 's/version: //')
          echo "Extracted version: $VERSION"
          echo "::set-output name=extracted_version::$VERSION"
      
      - name: Update CHANGELOG.md
        run: |
          dart run .github/scripts/update_changelog.dart "${{ steps.get_version.outputs.extracted_version }}" "- Date: $(date +%Y-%m-%d)"
      
      - name: Commit and Push Changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add CHANGELOG.md
          git commit -m "Automatically update CHANGELOG.md for version ${{ steps.get_version.outputs.extracted_version }}"
          git push
